<?xml version="1.0"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://localhost/test/web-service/server/service.php" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap-enc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="Calculator" targetNamespace="http://localhost/test/web-service/server/service.php">
  <types>
    <xsd:schema targetNamespace="http://localhost/test/web-service/server/service.php">
      <xsd:import namespace="http://schemas.xmlsoap.org/soap/encoding/"/>
    </xsd:schema>
  </types>
  <portType name="CalculatorPort">
    <operation name="sum">
      <input message="tns:sumIn"/>
    </operation>
    <operation name="minus">
      <input message="tns:minusIn"/>
    </operation>
  </portType>
  <binding name="CalculatorBinding" type="tns:CalculatorPort">
    <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="sum">
      <soap:operation soapAction="http://localhost/test/web-service/server/service.php#sum"/>
      <input>
        <soap:body use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://localhost/test/web-service/server/service.php"/>
      </input>
      <output>
        <soap:body use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://localhost/test/web-service/server/service.php"/>
      </output>
    </operation>
    <operation name="minus">
      <soap:operation soapAction="http://localhost/test/web-service/server/service.php#minus"/>
      <input>
        <soap:body use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://localhost/test/web-service/server/service.php"/>
      </input>
      <output>
        <soap:body use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://localhost/test/web-service/server/service.php"/>
      </output>
    </operation>
  </binding>
  <service name="CalculatorService">
    <port name="CalculatorPort" binding="tns:CalculatorBinding">
      <soap:address location="http://localhost/test/web-service/server/service.php"/>
    </port>
  </service>
  <message name="sumIn">
    <part name="x" type="xsd:anyType"/>
    <part name="y" type="xsd:anyType"/>
  </message>
  <message name="minusIn">
    <part name="x" type="xsd:anyType"/>
    <part name="y" type="xsd:anyType"/>
  </message>
</definitions>
